### ISSUE TITLE
Not found mservice/payment/loader.php

### ISSUE THREAD

**Issue by nguyendinhvulam** [xuandinhgl/momo-payment-gateway#1]
I'm not found mservice/payment/loader.php

Fatal error: require_once(): Failed opening required '..\wp-content\plugins\momo-payment-gateway-master/vendor/mservice/payment/loader.php' (include_path='D:\xampp\php\PEAR') in ..\wp-content\plugins\momo-payment-gateway-master\includes\class-dht-momo.php on line 122

**Comment by xuandinhgl** [comment]
Bug fixed
